# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_param chipscope.maxJobs 4
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/it/project_1/project_1.cache/wt [current_project]
set_property parent.project_path /home/it/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:arty-a7-100:part0:1.1 [current_project]
set_property ip_output_repo /home/it/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  /home/it/project_1/project_1.srcs/sources_1/imports/it/chip_design/commoncore/digitaldesign/project/ALU/ALU.srcs/sources_1/new/ALU.sv
  /home/it/project_1/project_1.srcs/sources_1/imports/it/Downloads/Assignment3-Counter/Assignment3-Counter.srcs/sources_1/new/Counter.sv
  {/home/it/project_1/project_1.srcs/sources_1/imports/new/D Flip_Flop.sv}
  /home/it/project_1/project_1.srcs/sources_1/imports/it/Downloads/Assignment3-Instruction_Memory/Assignment3-Instruction_Memory.srcs/sources_1/new/Data_Memory.sv
  /home/it/project_1/project_1.srcs/sources_1/imports/new/Dlatch.sv
  /home/it/project_1/project_1.srcs/sources_1/imports/it/Downloads/Assignment3-Instruction_Memory/Assignment3-Instruction_Memory.srcs/sources_1/new/Instruction_Memory.sv
  /home/it/project_1/project_1.srcs/sources_1/imports/it/Downloads/Assignment3-Multiplexers/Assignment3-Multiplexers.srcs/sources_1/new/Multiplexers.sv
  /home/it/project_1/project_1.srcs/sources_1/new/clock_divider.sv
  /home/it/project_1/project_1.srcs/sources_1/imports/src/counter_n_bit.sv
  /home/it/project_1/project_1.srcs/sources_1/imports/it/chip_design/commoncore/digitaldesign/project/decoder/decoder.srcs/sources_1/new/decoder.sv
  /home/it/project_1/project_1.srcs/sources_1/imports/it/chip_design/commoncore/digitaldesign/project/ALU/ALU.srcs/sources_1/new/fulladder.sv
  /home/it/project_1/project_1.srcs/sources_1/imports/it/chip_design/commoncore/digitaldesign/project/ALU/ALU.srcs/sources_1/new/halfadder.sv
  /home/it/project_1/project_1.srcs/sources_1/imports/it/chip_design/commoncore/digitaldesign/project/decoder/decoder.srcs/sources_1/new/instructions_decoder.sv
  /home/it/project_1/project_1.srcs/sources_1/imports/it/Downloads/Assignment3-Register/Assignment3-Register.srcs/sources_1/imports/new/n_bit_register.sv
  /home/it/project_1/project_1.srcs/sources_1/imports/src/sev_seg.sv
  /home/it/project_1/project_1.srcs/sources_1/imports/src/sev_seg_controller.sv
  /home/it/project_1/project_1.srcs/sources_1/imports/src/sev_seg_decoder.sv
  /home/it/project_1/project_1.srcs/sources_1/new/sevdecoder.sv
  /home/it/project_1/project_1.srcs/sources_1/new/K2_Microprosser.sv
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/it/project_1/project_1.srcs/constrs_1/imports/src/pin-assignment.xdc
set_property used_in_implementation false [get_files /home/it/project_1/project_1.srcs/constrs_1/imports/src/pin-assignment.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top K2_Microprosser -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef K2_Microprosser.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file K2_Microprosser_utilization_synth.rpt -pb K2_Microprosser_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
